#ServerProperties
server:
  port: 8080
  servlet:
    context-path: /api_management
#spring配置
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/api_management?serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    # 123
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: mydb
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000


#mybatis配置
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.apiSystem.entity
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true

#pagehelper分页插件配置
pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#日志配置
logging:
  file:
    path: E:\IDEAWorkplace\API-System-01\systemlog
  level:
    com.apiSystem.mapper: debug
    com.apiSystem.test: debug




